### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by GuitarZH** [cszhilu1998/SelfHDR#1]
Thanks for your excellent work. Really surprising!
When will you plan to release the codebase?

**Comment by cszhilu1998** [comment]
We plan to release the code after the CVPR deadline.

**Comment by cszhilu1998** [comment]
The code has been released. Thanks for your attention.

**Comment by cszhilu1998** [comment]
> Thanks for your excellent work. Really surprising! When will you plan to release the codebase?

The code has been released. Thanks for your attention.

**Comment by GuitarZH** [comment]
Thanks for your amazing work!
