### ISSUE TITLE
How to calculate psnr and ssim of Y_color and Y_stru?

### ISSUE THREAD

**Issue by Chenrf1121** [cszhilu1998/SelfHDR#3]
Dear researchers, I confused about training stage, and how can I save the mid images(Y_color, Y_stru)? 
Begging your response!

**Comment by cszhilu1998** [comment]
Y_color has been released in 'Training_align' and  'Test_align' folders in the [dataset](https://pan.baidu.com/s/1XsIiXmN_5wn_dfz4SsyTNA?pwd=i7fc#list/path=%2Fsharelink257376906-321807932082495%2FHDR%2FKalantari17&parentPath=%2Fsharelink257376906-321807932082495). Y_stru can be obtained by Line 33-37 in [train.sh](https://github.com/cszhilu1998/SelfHDR/blob/master/train.sh).
