### ISSUE TITLE
How to get the  model/dataset files without baidu account?

### ISSUE THREAD

**Issue by guferreti** [cszhilu1998/SelfHDR#4]
Can you help me with those files, I'm from brazil and I cannot create an Baidu account, may I send you in any a link(via email or the way you want) to my onedrive folder and you send it to me?

**Comment by cszhilu1998** [comment]
Please try [https://passport.baidu.com/v2/?reg &overseas=1](https://passport.baidu.com/v2/?reg&overseas=1) to register a Baidu account. Mobile phone numbers starting with "+55" seem to represent Brazil.

**Comment by guferreti** [comment]
Directly through this website I cannot enter the entire phone number and trying through other option I get that only phones from macau, taiwan and china works even with the +55 option

**Comment by guferreti** [comment]
Tried with wechat as well but it still asks for a phone number on baidu

**Comment by cszhilu1998** [comment]
I upload all files to [TeraBox](https://terabox.com). Please click [https://terabox.com/s/1VxpH6Ze72sZY2W0MJXwILw](https://terabox.com/s/1VxpH6Ze72sZY2W0MJXwILw) to download.

**Comment by guferreti** [comment]
Thank you very much!

**Comment by ManuBN786** [comment]
Now Terabox is asking to purchase a premium account. 

Is there any other way to download?
