### ISSUE TITLE
感谢你们出色的工作！想询问一下你们有baseline的测试和训练代码吗

### ISSUE THREAD

**Issue by wuhang03** [cszhilu1998/SelfHDR#5]
你们的代码写的很棒！简洁且一目了然
我看到你们论文中baseline的指标与其论文中并不一样，猜测你们应该是自己复现了模型并重新测试了
请问你们方便提供一下AHDRNet的有监督训练和测试代码吗
因为我在使用其官方仓库进行复现的过程中遇到了一些问题
如能提供我将不胜感激！

**Comment by cszhilu1998** [comment]
It seems that this can be achieved with a simple modification of our codes. You can try to load ground-truth in [sig17align_dataset.py](https://github.com/cszhilu1998/SelfHDR/blob/master/data/sig17align_dataset.py) and modify ‘backward’ function [selfhdr1_model.py](https://github.com/cszhilu1998/SelfHDR/blob/master/models/selfhdr1_model.py).

**Comment by wuhang03** [comment]
> It seems that this can be achieved with a simple modification of our codes. You can try to load ground-truth in [sig17align_dataset.py](https://github.com/cszhilu1998/SelfHDR/blob/master/data/sig17align_dataset.py) and modify ‘backward’ function [selfhdr1_model.py](https://github.com/cszhilu1998/SelfHDR/blob/master/models/selfhdr1_model.py).

感谢您的回复！
我已经按照您说的方式对代码进行了修改，并初步运行起来了
现在想使用您给出的ckpt进行微调，但是在加载ckpt并继续训练的过程中出现了下列提示
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/AHDR_ckpt/ahdrnet_stage1/SelfHDR_optimizer_Adam.pth'
想问一下这个optimizer_Adam.pth文件对微调过程是否有影响，还是说直接重新初始化一个就行
十分感谢！

**Comment by cszhilu1998** [comment]
You can reinitialize one. In addition, It may be more appropriate to train the model from scratch, and it will not take long.

**Comment by wuhang03** [comment]
好的  感谢您的回复！
我会按照您说的方式进行尝试
