### ISSUE TITLE
exposure time

### ISSUE THREAD

**Issue by aaronwuganglyu** [cszhilu1998/SelfHDR#6]
hi, thanks for your great work. 
In your code, ldr_to_hdr(imgs, expo, gamma), you set gamma to be 2. I am wondering how you chooses this parameter? If for different test images, should I change this parameter and how to determine this value?
In addition, I see "syn_hdr" function in your code but do not see where it is used, do you use some extra scripts to create some hdr images as ground truth for model training in the first or second stages?

Thanks for your time

**Comment by cszhilu1998** [comment]
The gamma parameter is set to **2.2**, which follows the previous HDR reconstruction works. When testing other images, you may need to use a specific gamma parameter from the camera ISP. However, in most cases, **2.2** is appropriate.

 "syn_hdr" function can be used for generating 𝒀𝑐𝑜𝑙𝑜𝑟 in the first stage, and we directly provide 𝒀𝑐𝑜𝑙𝑜𝑟 in the folders ending with `_align`  in the [link](https://www.terabox.com/chinese/sharing/link?surl=VxpH6Ze72sZY2W0MJXwILw&path=%2FDataset%2FHDR%2FKalantari17).

**Comment by aaronwuganglyu** [comment]
get it, thanks
